# Generated by Django 4.2.3 on 2023-07-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_field_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='working_day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AddField(
            model_name='field',
            name='working_hours',
            field=models.IntegerField(choices=[(16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21)], default=16.0),
        ),
    ]
