# Generated by Django 4.2.3 on 2023-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_field_working_day_field_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='working_day',
            new_name='end_working_day',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='working_hours',
            new_name='end_working_hour',
        ),
        migrations.AddField(
            model_name='field',
            name='start_working_day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AddField(
            model_name='field',
            name='start_working_hour',
            field=models.IntegerField(choices=[(16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21)], default=16),
        ),
    ]
