# Generated by Django 4.2.3 on 2023-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_working_day_field_end_working_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='end_working_day',
            field=models.IntegerField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='field',
            name='start_working_day',
            field=models.IntegerField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=1),
        ),
    ]
