# Generated by Django 4.2.3 on 2023-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_field_end_working_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='price_per_hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
