# Generated by Django 4.2.3 on 2023-07-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_working_day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_working_hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_working_day',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_working_hour',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_hour',
            field=models.IntegerField(choices=[(16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')]),
        ),
    ]
