# Generated by Django 4.2.3 on 2023-08-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_event_max_sign_ups_eventsignup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSignUp',
        ),
    ]
