# Generated by Django 4.2.3 on 2023-08-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_delete_eventsignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='sport',
        ),
    ]
