# Generated by Django 4.2.3 on 2023-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_rename_category_event_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='sport',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_sport',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis')], max_length=100),
        ),
    ]
