# Generated by Django 4.2.3 on 2023-08-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_event_sport_alter_field_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_sport',
            field=models.CharField(blank=True, choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Tennis', 'Tennis')], max_length=100),
        ),
    ]
